# System-wide configuration
description: "Legal RAG system with improved context precision"

components:
  embeddings:
    model: "sentence-transformers/all-mpnet-base-v2"
    
  llm:
    provider: "azure_openai"
    model: "gpt-4o"
    deployment: "gpt-4o"
    api_version: "2024-06-01"
    
  retrieval:
    reranker_enabled: true
    reranker_model: "cross-encoder/ms-marco-MiniLM-L-6-v2"
    
  prompts:
    legal_system: "legal_v1.0.0"
    legal_user: "legal_v1.0.0"
    
  pipeline:
    chunk_size: 1000
    overlap: 150
    top_k: 7
    
metadata:
  created_by: "areisde"
  created_at: "2025-08-11T12:00:00Z"
  
validation:
  min_ragas_faithfulness: 0.8
  min_ragas_relevancy: 0.75
